/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TaskManager {
  export type TaskStruct = {
    id: BigNumberish;
    requester: AddressLike;
    agentId: BigNumberish;
    description: string;
    params: string;
    result: string;
    status: BigNumberish;
    fee: BigNumberish;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
    parentTaskId: BigNumberish;
    depth: BigNumberish;
  };

  export type TaskStructOutput = [
    id: bigint,
    requester: string,
    agentId: bigint,
    description: string,
    params: string,
    result: string,
    status: bigint,
    fee: bigint,
    createdAt: bigint,
    completedAt: bigint,
    parentTaskId: bigint,
    depth: bigint
  ] & {
    id: bigint;
    requester: string;
    agentId: bigint;
    description: string;
    params: string;
    result: string;
    status: bigint;
    fee: bigint;
    createdAt: bigint;
    completedAt: bigint;
    parentTaskId: bigint;
    depth: bigint;
  };
}

export interface TaskManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authority"
      | "completeTask"
      | "createTask"
      | "disputeTask"
      | "failTask"
      | "getRecentTasks"
      | "getRequesterTasks"
      | "getTask"
      | "getTaskCount"
      | "registry"
      | "requesterTasks"
      | "taskCount"
      | "tasks"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TaskAssigned"
      | "TaskCompleted"
      | "TaskCreated"
      | "TaskDisputed"
      | "TaskFailed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BigNumberish, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "failTask",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentTasks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequesterTasks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requesterTasks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "taskCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "failTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecentTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequesterTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requesterTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
}

export namespace TaskAssignedEvent {
  export type InputTuple = [taskId: BigNumberish, agentId: BigNumberish];
  export type OutputTuple = [taskId: bigint, agentId: bigint];
  export interface OutputObject {
    taskId: bigint;
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [taskId: BigNumberish, result: string];
  export type OutputTuple = [taskId: bigint, result: string];
  export interface OutputObject {
    taskId: bigint;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    requester: AddressLike,
    agentId: BigNumberish,
    description: string,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    requester: string,
    agentId: bigint,
    description: string,
    fee: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    requester: string;
    agentId: bigint;
    description: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDisputedEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskFailedEvent {
  export type InputTuple = [taskId: BigNumberish, reason: string];
  export type OutputTuple = [taskId: bigint, reason: string];
  export interface OutputObject {
    taskId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskManager extends BaseContract {
  connect(runner?: ContractRunner | null): TaskManager;
  waitForDeployment(): Promise<this>;

  interface: TaskManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authority: TypedContractMethod<[], [string], "view">;

  completeTask: TypedContractMethod<
    [taskId: BigNumberish, result: string],
    [void],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [
      agentId: BigNumberish,
      description: string,
      params: string,
      parentTaskId: BigNumberish,
      depth: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  disputeTask: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  failTask: TypedContractMethod<
    [taskId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  getRecentTasks: TypedContractMethod<
    [limit: BigNumberish],
    [TaskManager.TaskStructOutput[]],
    "view"
  >;

  getRequesterTasks: TypedContractMethod<
    [requester: AddressLike],
    [TaskManager.TaskStructOutput[]],
    "view"
  >;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [TaskManager.TaskStructOutput],
    "view"
  >;

  getTaskCount: TypedContractMethod<[], [bigint], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  requesterTasks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  taskCount: TypedContractMethod<[], [bigint], "view">;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        requester: string;
        agentId: bigint;
        description: string;
        params: string;
        result: string;
        status: bigint;
        fee: bigint;
        createdAt: bigint;
        completedAt: bigint;
        parentTaskId: bigint;
        depth: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<
    [taskId: BigNumberish, result: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      description: string,
      params: string,
      parentTaskId: BigNumberish,
      depth: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "disputeTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "failTask"
  ): TypedContractMethod<
    [taskId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecentTasks"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [TaskManager.TaskStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequesterTasks"
  ): TypedContractMethod<
    [requester: AddressLike],
    [TaskManager.TaskStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [TaskManager.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requesterTasks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "taskCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        requester: string;
        agentId: bigint;
        description: string;
        params: string;
        result: string;
        status: bigint;
        fee: bigint;
        createdAt: bigint;
        completedAt: bigint;
        parentTaskId: bigint;
        depth: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TaskAssigned"
  ): TypedContractEvent<
    TaskAssignedEvent.InputTuple,
    TaskAssignedEvent.OutputTuple,
    TaskAssignedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDisputed"
  ): TypedContractEvent<
    TaskDisputedEvent.InputTuple,
    TaskDisputedEvent.OutputTuple,
    TaskDisputedEvent.OutputObject
  >;
  getEvent(
    key: "TaskFailed"
  ): TypedContractEvent<
    TaskFailedEvent.InputTuple,
    TaskFailedEvent.OutputTuple,
    TaskFailedEvent.OutputObject
  >;

  filters: {
    "TaskAssigned(uint256,uint256)": TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;
    TaskAssigned: TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;

    "TaskCompleted(uint256,string)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(uint256,address,uint256,string,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDisputed(uint256)": TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;
    TaskDisputed: TypedContractEvent<
      TaskDisputedEvent.InputTuple,
      TaskDisputedEvent.OutputTuple,
      TaskDisputedEvent.OutputObject
    >;

    "TaskFailed(uint256,string)": TypedContractEvent<
      TaskFailedEvent.InputTuple,
      TaskFailedEvent.OutputTuple,
      TaskFailedEvent.OutputObject
    >;
    TaskFailed: TypedContractEvent<
      TaskFailedEvent.InputTuple,
      TaskFailedEvent.OutputTuple,
      TaskFailedEvent.OutputObject
    >;
  };
}
