/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentRegistry {
  export type AgentStruct = {
    owner: AddressLike;
    name: string;
    endpoint: string;
    category: string;
    capabilities: string;
    price: BigNumberish;
    reputation: BigNumberish;
    jobsCompleted: BigNumberish;
    jobsFailed: BigNumberish;
    totalEarned: BigNumberish;
    isActive: boolean;
    registeredAt: BigNumberish;
  };

  export type AgentStructOutput = [
    owner: string,
    name: string,
    endpoint: string,
    category: string,
    capabilities: string,
    price: bigint,
    reputation: bigint,
    jobsCompleted: bigint,
    jobsFailed: bigint,
    totalEarned: bigint,
    isActive: boolean,
    registeredAt: bigint
  ] & {
    owner: string;
    name: string;
    endpoint: string;
    category: string;
    capabilities: string;
    price: bigint;
    reputation: bigint;
    jobsCompleted: bigint;
    jobsFailed: bigint;
    totalEarned: bigint;
    isActive: boolean;
    registeredAt: bigint;
  };

  export type RatingStruct = {
    rater: AddressLike;
    score: BigNumberish;
    comment: string;
    timestamp: BigNumberish;
  };

  export type RatingStructOutput = [
    rater: string,
    score: bigint,
    comment: string,
    timestamp: bigint
  ] & { rater: string; score: bigint; comment: string; timestamp: bigint };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentByOwner"
      | "agentCount"
      | "agentRatings"
      | "agents"
      | "authority"
      | "discoverAgents"
      | "getActiveAgentsByCategory"
      | "getAgent"
      | "getAgentByOwner"
      | "getAgentCount"
      | "getAgentRatings"
      | "getAllActiveAgents"
      | "rateAgent"
      | "recordJobCompletion"
      | "recordJobFailure"
      | "registerAgent"
      | "setActive"
      | "setAuthority"
      | "updateAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRated"
      | "AgentRegistered"
      | "AgentStatusChanged"
      | "AgentUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentRatings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "authority", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "discoverAgents",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveAgentsByCategory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentRatings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllActiveAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rateAgent",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordJobCompletion",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordJobFailure",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentRatings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authority", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "discoverAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveAgentsByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentRatings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllActiveAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rateAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordJobCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordJobFailure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentRatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    rater: AddressLike,
    score: BigNumberish
  ];
  export type OutputTuple = [agentId: bigint, rater: string, score: bigint];
  export interface OutputObject {
    agentId: bigint;
    rater: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    name: string,
    category: string,
    price: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    name: string,
    category: string,
    price: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    name: string;
    category: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatusChangedEvent {
  export type InputTuple = [agentId: BigNumberish, isActive: boolean];
  export type OutputTuple = [agentId: bigint, isActive: boolean];
  export interface OutputObject {
    agentId: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentByOwner: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agentRatings: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint] & {
        rater: string;
        score: bigint;
        comment: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  agents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        owner: string;
        name: string;
        endpoint: string;
        category: string;
        capabilities: string;
        price: bigint;
        reputation: bigint;
        jobsCompleted: bigint;
        jobsFailed: bigint;
        totalEarned: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  authority: TypedContractMethod<[], [string], "view">;

  discoverAgents: TypedContractMethod<
    [capabilityFilter: string],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;

  getActiveAgentsByCategory: TypedContractMethod<
    [category: string],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;

  getAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;

  getAgentByOwner: TypedContractMethod<
    [owner: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;

  getAgentCount: TypedContractMethod<[], [bigint], "view">;

  getAgentRatings: TypedContractMethod<
    [agentId: BigNumberish],
    [AgentRegistry.RatingStructOutput[]],
    "view"
  >;

  getAllActiveAgents: TypedContractMethod<
    [],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;

  rateAgent: TypedContractMethod<
    [agentId: BigNumberish, score: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;

  recordJobCompletion: TypedContractMethod<
    [agentId: BigNumberish, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordJobFailure: TypedContractMethod<
    [agentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [
      name: string,
      endpoint: string,
      category: string,
      capabilities: string,
      price: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  setActive: TypedContractMethod<
    [agentId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  setAuthority: TypedContractMethod<
    [_authority: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgent: TypedContractMethod<
    [agentId: BigNumberish, endpoint: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentByOwner"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentRatings"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint] & {
        rater: string;
        score: bigint;
        comment: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        owner: string;
        name: string;
        endpoint: string;
        category: string;
        capabilities: string;
        price: bigint;
        reputation: bigint;
        jobsCompleted: bigint;
        jobsFailed: bigint;
        totalEarned: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "discoverAgents"
  ): TypedContractMethod<
    [capabilityFilter: string],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveAgentsByCategory"
  ): TypedContractMethod<
    [category: string],
    [AgentRegistry.AgentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentByOwner"
  ): TypedContractMethod<
    [owner: AddressLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentRatings"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [AgentRegistry.RatingStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllActiveAgents"
  ): TypedContractMethod<[], [AgentRegistry.AgentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "rateAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish, score: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordJobCompletion"
  ): TypedContractMethod<
    [agentId: BigNumberish, fee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordJobFailure"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      name: string,
      endpoint: string,
      category: string,
      capabilities: string,
      price: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setActive"
  ): TypedContractMethod<
    [agentId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthority"
  ): TypedContractMethod<[_authority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish, endpoint: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRated"
  ): TypedContractEvent<
    AgentRatedEvent.InputTuple,
    AgentRatedEvent.OutputTuple,
    AgentRatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatusChanged"
  ): TypedContractEvent<
    AgentStatusChangedEvent.InputTuple,
    AgentStatusChangedEvent.OutputTuple,
    AgentStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRated(uint256,address,uint8)": TypedContractEvent<
      AgentRatedEvent.InputTuple,
      AgentRatedEvent.OutputTuple,
      AgentRatedEvent.OutputObject
    >;
    AgentRated: TypedContractEvent<
      AgentRatedEvent.InputTuple,
      AgentRatedEvent.OutputTuple,
      AgentRatedEvent.OutputObject
    >;

    "AgentRegistered(uint256,address,string,string,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatusChanged(uint256,bool)": TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;
    AgentStatusChanged: TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;

    "AgentUpdated(uint256)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
  };
}
