/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as taskManagerSol from "./TaskManager.sol";
export type { taskManagerSol };
export type { AgentRegistry } from "./AgentRegistry";
export type { AgentVault } from "./AgentVault";
export * as factories from "./factories";
export { AgentRegistry__factory } from "./factories/AgentRegistry__factory";
export { AgentVault__factory } from "./factories/AgentVault__factory";
export type { IAgentRegistry } from "./TaskManager.sol/IAgentRegistry";
export { IAgentRegistry__factory } from "./factories/TaskManager.sol/IAgentRegistry__factory";
export type { TaskManager } from "./TaskManager.sol/TaskManager";
export { TaskManager__factory } from "./factories/TaskManager.sol/TaskManager__factory";
